// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxmcATpQ8ptw3tHPJlqMCc-J35UgFnMqM',
    appId: '1:976911136345:web:45123bc8eca0a9ad3d6348',
    messagingSenderId: '976911136345',
    projectId: 'riba-2daa7',
    authDomain: 'riba-2daa7.firebaseapp.com',
    storageBucket: 'riba-2daa7.firebasestorage.app',
    measurementId: 'G-2LJXV592EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnuTSDQe_reF1RrMuGqCyIZhSecWuHpOc',
    appId: '1:976911136345:android:4509ad70fb7874343d6348',
    messagingSenderId: '976911136345',
    projectId: 'riba-2daa7',
    storageBucket: 'riba-2daa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZyK1twMtVL1WscrLDryaZ9X_AQiwxjfA',
    appId: '1:976911136345:ios:1c42cf9e3a31936e3d6348',
    messagingSenderId: '976911136345',
    projectId: 'riba-2daa7',
    storageBucket: 'riba-2daa7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZyK1twMtVL1WscrLDryaZ9X_AQiwxjfA',
    appId: '1:976911136345:ios:1c42cf9e3a31936e3d6348',
    messagingSenderId: '976911136345',
    projectId: 'riba-2daa7',
    storageBucket: 'riba-2daa7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxmcATpQ8ptw3tHPJlqMCc-J35UgFnMqM',
    appId: '1:976911136345:web:013d0690a154fa153d6348',
    messagingSenderId: '976911136345',
    projectId: 'riba-2daa7',
    authDomain: 'riba-2daa7.firebaseapp.com',
    storageBucket: 'riba-2daa7.firebasestorage.app',
    measurementId: 'G-8MZSQ5EJ1L',
  );
}
